# Generated by Django 5.2.16 on 2026-07-25 00:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('check_in', models.DateField(verbose_name='Дата заезда')),
                ('check_out', models.DateField(verbose_name='Дата выезда')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('telegram', models.CharField(blank=True, max_length=255, verbose_name='Telegram')),
                ('guest_num', models.IntegerField(default=1, verbose_name='Количество гостей')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('options', models.JSONField(blank=True, default=dict, help_text='Выбранные доп. услуги в момент бронирования')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Цена за ночь на момент бронирования', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('extras_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Стоимость доп. услуг на момент бронирования', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Итоговая цена на момент бронирования', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='houses.housepage')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
