# Generated by Django 5.2.16 on 2026-07-25 00:44

import django.db.models.deletion
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('dacha.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('venue', models.TextField(blank=True, verbose_name='Место')),
                ('venue_notes', models.TextField(blank=True, help_text='Дополнительные инструкции: через какой въезд, что захватить, особые указания', verbose_name='Заметки как добраться')),
                ('map_link', models.URLField(blank=True, help_text='Ссылка на Яндекс.Карты/Google Maps с местом', verbose_name='Ссылка на карту')),
                ('summary', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('show_countdown', models.BooleanField(default=True, verbose_name='Показывать обратный отсчёт')),
                ('expected_temperature', models.CharField(blank=True, help_text='Например: "14°C"', max_length=20, verbose_name='Ожидаемая температура')),
                ('weather_note', models.CharField(blank=True, help_text='Например: "Прохладный лесной вечер"', max_length=100, verbose_name='Заметка о погоде')),
                ('special_tag', models.CharField(blank=True, help_text='Например: "HOT", "NEW", "FREE"', max_length=50, verbose_name='Тег события')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('info_card', 6), ('faq', 8), ('cta', 10), ('amenity_list', 13)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('dacha.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'info', 'help_text': "Material Symbol name e.g. 'checkroom', 'local_cafe', 'chair'", 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('icon', 3), ('title', 4), ('content', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 8: ('wagtail.blocks.StructBlock', [[('question', 7), ('answer', 5)]], {}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Apply glow effect and gradient border', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 5), ('highlighted', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'default': 'check', 'help_text': "Material Symbol name (e.g. 'checkroom', 'local_cafe', 'chair', 'confirmation_number')", 'max_length': 50, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('icon', 11), ('label', 4)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='EventDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='Марка/цвет авто')),
                ('car_type', models.CharField(blank=True, max_length=50, verbose_name='Тип авто')),
                ('seats_total', models.PositiveIntegerField(default=4, verbose_name='Всего мест')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата выезда')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Время выезда')),
                ('departure_location', models.CharField(blank=True, max_length=200, verbose_name='Откуда')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Дата обратно')),
                ('return_time', models.TimeField(blank=True, null=True, verbose_name='Время обратно')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Отменено')),
                ('contact_preference', models.CharField(choices=[('telegram', 'Telegram'), ('phone', 'Телефон'), ('both', 'Оба')], default='telegram', max_length=20, verbose_name='Предпочтение связи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='events.eventpage')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='CarpoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('pickup_location', models.CharField(blank=True, max_length=200, verbose_name='Откуда')),
                ('flexible_time', models.BooleanField(default=False, verbose_name='Гибкое время')),
                ('seats_needed', models.PositiveIntegerField(default=1, verbose_name='Сколько мест')),
                ('can_share_gas', models.BooleanField(default=False, verbose_name='Могу скинуться')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_requests', to='events.eventpage')),
            ],
            options={
                'verbose_name': 'Ищу попутку',
                'verbose_name_plural': 'Ищу попутку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RidePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('seats', models.PositiveIntegerField(default=1, verbose_name='Мест')),
                ('pickup_location', models.CharField(blank=True, max_length=200, verbose_name='Откуда заберет')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='events.eventdriver')),
            ],
            options={
                'verbose_name': 'Попутчик',
                'verbose_name_plural': 'Попутчики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxiPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=100, verbose_name='Организатор')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('pickup_location', models.CharField(max_length=200, verbose_name='Точка сбора')),
                ('departure_date', models.DateField(verbose_name='Дата')),
                ('departure_time', models.TimeField(verbose_name='Время')),
                ('max_passengers', models.PositiveIntegerField(default=4, verbose_name='Макс. пассажиров')),
                ('estimated_price', models.PositiveIntegerField(default=0, verbose_name='Цена с человека')),
                ('service', models.CharField(choices=[('yandex', 'Яндекс'), ('citymobil', 'Ситимобил'), ('other', 'Другое')], default='yandex', max_length=20, verbose_name='Сервис')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_pools', to='events.eventpage')),
            ],
            options={
                'verbose_name': 'Такси-пул',
                'verbose_name_plural': 'Такси-пулы',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='TaxiPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('seats', models.PositiveIntegerField(default=1, verbose_name='Мест')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='events.taxipool')),
            ],
            options={
                'verbose_name': 'Пассажир такси',
                'verbose_name_plural': 'Пассажиры такси',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('status', models.CharField(choices=[('going', 'Иду'), ('maybe', 'Возможно'), ('not_going', 'Не смогу')], default='going', max_length=20, verbose_name='Статус')),
                ('guests_count', models.PositiveIntegerField(default=0, verbose_name='Гости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.eventpage')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVP-записи',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'name')},
            },
        ),
    ]
