# Generated by Django 5.2.16 on 2026-07-29 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_account_rsvp_link'),
        ('events', '0003_rsvp_secret_key_waiting_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvps', to='core.useraccount'),
        ),
    ]
