FROM python:3.12-slim-bookworm

# Установка системных зависимостей
RUN apt-get update && apt-get install -y \
    gettext \
    libpq-dev \
    gcc \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

# Установка uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy

WORKDIR /app

# Копируем файлы зависимостей
COPY pyproject.toml uv.lock* /app/

# Устанавливаем зависимости СИСТЕМНО (в Docker это ок и проще для Gunicorn)
RUN uv pip install --system -r pyproject.toml

# Копируем код проекта
COPY . /app/
RUN chmod +x /app/justfile

# Открываем порт
EXPOSE 8000

# Запускаем через just
CMD ["just", "entrypoint"]