# Generated by Django 5.2.16 on 2026-07-24 09:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='faq_items',
            field=wagtail.fields.StreamField([('faq', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1)]], {})}),
        ),
        migrations.AlterField(
            model_name='faqpage',
            name='intro',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('dacha.blocks.RichTextBlock', (), {})}),
        ),
    ]
