import { notFound } from 'next/navigation'
import { getPayloadClient } from '@/lib/payload'
import { BlockRenderer } from '@/lib/blocks-registry'
import { Countdown } from '@/components/event/Countdown'
import { RsvpWidget } from '@/components/event/RsvpWidget'
import { ContributionWidget } from '@/components/event/ContributionWidget'
import { CarpoolSection } from '@/components/event/CarpoolSection'
import { AttendeesList, type Attendee } from '@/components/event/AttendeesList'

// Force runtime render so the Docker build doesn't need a live DB.
// Access control honors publish/draft per request.
export const dynamic = 'force-dynamic'

type HeroImage = {
  alt?: string
  caption?: string
  url?: string
  sizes?: { hero?: { url?: string } }
}

type Props = {
  params: Promise<{ slug: string }>
}

export default async function EventDetailPage({ params }: Props) {
  const { slug } = await params
  const payload = await getPayloadClient()
  const result = await payload.find({
    collection: 'events',
    where: { slug: { equals: slug } },
    limit: 1,
    depth: 2,
  })
  const event = result.docs[0]
  if (!event) notFound()

  const eventId = String((event as { id: string | number }).id)
  const eventSlug = String((event as { slug: string }).slug)
  const showContributionWidget = Boolean((event as { showContributionWidget?: boolean }).showContributionWidget)
  const contributionGoal =
    typeof (event as { contributionGoal?: number }).contributionGoal === 'number'
      ? ((event as { contributionGoal: number }).contributionGoal as number)
      : null
  const yoomoneyEnabled = Boolean(process.env.YOOMONEY_WALLET && process.env.YOOMONEY_CLIENT_ID)

  // Hero image — prefer the `hero` size (1920×1080) generated by Payload's
  // sharp pipeline, fall back to the original URL. `alt` is required at the
  // field level, so we always have a value.
  const hero = (event as { heroImage?: HeroImage | null }).heroImage
  const heroUrl = hero?.sizes?.hero?.url || hero?.url

  // Fetch RSVPs for the attendees list (going + maybe + waiting, sorted by createdAt).
  const rsvpsRes = await payload.find({
    collection: 'event-rsvps',
    where: { event: { equals: eventId } },
    sort: 'createdAt',
    limit: 200,
    depth: 0,
    overrideAccess: true,
  })
  const attendees: Attendee[] = rsvpsRes.docs.map((r) => {
    const rsvp = r as {
      id: string | number
      name: string
      status: Attendee['status']
      guestsCount: number
    }
    return {
      id: rsvp.id,
      name: rsvp.name,
      status: rsvp.status,
      guestsCount: rsvp.guestsCount ?? 1,
    }
  })

  // Fetch confirmed contributions for the public summary widget.
  const initialContributions = showContributionWidget
    ? await payload
        .find({
          collection: 'event-contributions',
          where: {
            event: { equals: eventId },
            status: { equals: 'confirmed' },
          },
          sort: '-confirmedAt',
          limit: 500,
          depth: 0,
          overrideAccess: true,
        })
        .then((res) => {
          type Confirmed = {
            name: string
            amount: number
            message?: string | null
            confirmedAt?: string | null
          }
          return {
            total: res.docs.reduce((s, c) => s + ((c as Confirmed).amount ?? 0), 0),
            contributions: (res.docs as Confirmed[]).map((c) => ({
              name: c.name,
              amount: c.amount,
              message: c.message ?? null,
              confirmedAt: c.confirmedAt ?? null,
            })),
          }
        })
    : { total: 0, contributions: [] }

  return (
    <article className="max-w-4xl mx-auto px-4 py-12">
      {heroUrl && (
        <div className="relative w-full aspect-video mb-8 rounded-2xl overflow-hidden bg-base-300">
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={heroUrl}
            alt={hero?.alt ?? event.title}
            className="w-full h-full object-cover"
          />
          {hero?.caption && (
            <div className="absolute bottom-0 left-0 right-0 px-4 py-2 bg-gradient-to-t from-black/70 to-transparent text-sm text-white/90">
              {hero.caption}
            </div>
          )}
        </div>
      )}

      <header className="mb-8">
        <p className="text-sm text-base-content/60">
          {new Date((event as any).startDate).toLocaleDateString('ru-RU', {
            day: 'numeric', month: 'long', year: 'numeric',
          })}
          {(event as any).startTime && `, ${(event as any).startTime}`}
        </p>
        <h1 className="text-4xl font-bold mt-2">{event.title}</h1>
        {(event as any).venue && <p className="text-lg text-base-content/80 mt-2">📍 {(event as any).venue}</p>}
        {(event as any).summary && <p className="text-base-content/70 mt-4">{(event as any).summary}</p>}

        {(event as any).showCountdown && (event as any).startDate && (
          <div className="mt-4">
            <Countdown targetDate={(event as any).startDate} />
          </div>
        )}
      </header>

      <div className="grid lg:grid-cols-3 gap-8 mb-12">
        <aside className="lg:col-span-1 space-y-6">
          <RsvpWidget eventId={eventId} eventSlug={eventSlug} />
          <ContributionWidget
            eventId={eventId}
            eventSlug={eventSlug}
            showWidget={showContributionWidget}
            contributionGoal={contributionGoal}
            initialSummary={initialContributions}
            yoomoneyEnabled={yoomoneyEnabled}
          />
        </aside>

        <section className="lg:col-span-2 space-y-6">
          <div className="glass-card p-6">
            <h3 className="text-xl font-serif font-bold mb-4">
              <span className="material-symbols-outlined align-middle mr-2">
                groups
              </span>
              Уже идут ({attendees.filter((a) => a.status === 'going').length})
            </h3>
            <AttendeesList attendees={attendees} />
          </div>
        </section>
      </div>

      <section className="mb-12">
        <h2 className="text-2xl font-serif font-bold mb-4">
          <span className="material-symbols-outlined align-middle mr-2">
            directions_car
          </span>
          Попутки и такси
        </h2>
        <CarpoolSection eventId={eventId} eventSlug={eventSlug} />
      </section>

      <BlockRenderer blocks={(event as any).body as any} />
    </article>
  )
}
