# Generated by Django 5.2.16 on 2026-07-23 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='show_countdown',
            field=models.BooleanField(default=True, verbose_name='Показывать обратный отсчёт'),
        ),
    ]
