# Generated by Django 5.2.16 on 2026-07-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdriver',
            name='cancel_token',
            field=models.CharField(blank=True, default='', help_text='Секретный токен для отмены поездки. Заполняется автоматически.', max_length=64, verbose_name='Токен отмены'),
        ),
    ]
