# Generated by Django 5.2.16 on 2026-07-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventpage_show_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='venue',
            field=models.TextField(blank=True),
        ),
    ]
