# Generated by Django 5.2.16 on 2026-07-29 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_driver_cancel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='rsvp_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Если указано, новые RSVPs сверх лимита попадут в очередь. Оставьте пустым — без лимита.', null=True, verbose_name='Лимит RSVPs'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='secret_key',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='status',
            field=models.CharField(choices=[('going', 'Иду'), ('maybe', 'Возможно'), ('not_going', 'Не смогу'), ('waiting', 'В очереди')], default='going', max_length=20, verbose_name='Статус'),
        ),
    ]
