# Generated by Django 5.2.16 on 2026-07-24 09:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_change_venue_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('info_card', 6), ('faq', 8), ('cta', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title'}), 1: ('dacha.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'info', 'help_text': "Material Symbol name e.g. 'checkroom', 'local_cafe', 'chair'", 'max_length': 50, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 5: ('wagtail.blocks.RichTextBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('icon', 3), ('title', 4), ('content', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 8: ('wagtail.blocks.StructBlock', [[('question', 7), ('answer', 5)]], {}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Apply glow effect and gradient border', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 4), ('text', 5), ('highlighted', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='eventsindexpage',
            name='intro',
            field=wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('dacha.blocks.RichTextBlock', (), {})}),
        ),
    ]
