# Generated by Django 5.2.16 on 2026-07-24 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_extend_event_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='expected_temperature',
            field=models.CharField(blank=True, help_text='Например: "14°C"', max_length=20, verbose_name='Ожидаемая температура'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='weather_note',
            field=models.CharField(blank=True, help_text='Например: "Прохладный лесной вечер"', max_length=100, verbose_name='Заметка о погоде'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='venue',
            field=models.TextField(blank=True, verbose_name='Место'),
        ),
        migrations.CreateModel(
            name='EventDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('car_model', models.CharField(blank=True, max_length=100, verbose_name='Марка авто')),
                ('seats_total', models.PositiveIntegerField(default=4, verbose_name='Всего мест')),
                ('seats_taken', models.PositiveIntegerField(default=0, verbose_name='Занято')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Время выезда')),
                ('departure_location', models.CharField(blank=True, max_length=200, verbose_name='Откуда')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='events.eventpage')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['departure_time'],
            },
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('status', models.CharField(choices=[('going', 'Иду'), ('maybe', 'Возможно'), ('not_going', 'Не смогу')], default='going', max_length=20, verbose_name='Статус')),
                ('guests_count', models.PositiveIntegerField(default=0, verbose_name='Гости')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.eventpage')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVP-записи',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'name')},
            },
        ),
    ]
