# Generated by Django 5.2.16 on 2026-07-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventpage_special_tag_alter_eventpage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdriver',
            options={'ordering': ['departure_date', 'departure_time'], 'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.RemoveField(
            model_name='eventdriver',
            name='seats_taken',
        ),
        migrations.AddField(
            model_name='eventdriver',
            name='car_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип авто'),
        ),
        migrations.AddField(
            model_name='eventdriver',
            name='contact_preference',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('phone', 'Телефон'), ('both', 'Оба')], default='telegram', max_length=20, verbose_name='Предпочтение связи'),
        ),
        migrations.AddField(
            model_name='eventdriver',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
        migrations.AddField(
            model_name='eventdriver',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Отменено'),
        ),
        migrations.AddField(
            model_name='eventdriver',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='eventdriver',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата обратно'),
        ),
        migrations.AddField(
            model_name='eventdriver',
            name='return_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время обратно'),
        ),
        migrations.AddField(
            model_name='eventdriver',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='eventdriver',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Марка/цвет авто'),
        ),
        migrations.CreateModel(
            name='CarpoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('pickup_location', models.CharField(blank=True, max_length=200, verbose_name='Откуда')),
                ('flexible_time', models.BooleanField(default=False, verbose_name='Гибкое время')),
                ('seats_needed', models.PositiveIntegerField(default=1, verbose_name='Сколько мест')),
                ('can_share_gas', models.BooleanField(default=False, verbose_name='Могу скинуться')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_requests', to='events.eventpage')),
            ],
            options={
                'verbose_name': 'Ищу попутку',
                'verbose_name_plural': 'Ищу попутку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RidePassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('seats', models.PositiveIntegerField(default=1, verbose_name='Мест')),
                ('pickup_location', models.CharField(blank=True, max_length=200, verbose_name='Откуда заберет')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='events.eventdriver')),
            ],
            options={
                'verbose_name': 'Попутчик',
                'verbose_name_plural': 'Попутчики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaxiPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=100, verbose_name='Организатор')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('pickup_location', models.CharField(max_length=200, verbose_name='Точка сбора')),
                ('departure_date', models.DateField(verbose_name='Дата')),
                ('departure_time', models.TimeField(verbose_name='Время')),
                ('max_passengers', models.PositiveIntegerField(default=4, verbose_name='Макс. пассажиров')),
                ('estimated_price', models.PositiveIntegerField(default=0, verbose_name='Цена с человека')),
                ('service', models.CharField(choices=[('yandex', 'Яндекс'), ('citymobil', 'Ситимобил'), ('other', 'Другое')], default='yandex', max_length=20, verbose_name='Сервис')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxi_pools', to='events.eventpage')),
            ],
            options={
                'verbose_name': 'Такси-пул',
                'verbose_name_plural': 'Такси-пулы',
                'ordering': ['departure_date', 'departure_time'],
            },
        ),
        migrations.CreateModel(
            name='TaxiPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('seats', models.PositiveIntegerField(default=1, verbose_name='Мест')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='events.taxipool')),
            ],
            options={
                'verbose_name': 'Пассажир такси',
                'verbose_name_plural': 'Пассажиры такси',
                'ordering': ['-created_at'],
            },
        ),
    ]
