# Generated by Django 5.2.16 on 2026-07-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_add_carpool_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='map_link',
            field=models.URLField(blank=True, help_text='Ссылка на Яндекс.Карты/Google Maps с местом', verbose_name='Ссылка на карту'),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='venue_notes',
            field=models.TextField(blank=True, help_text='Дополнительные инструкции: через какой въезд, что захватить, особые указания', verbose_name='Заметки как добраться'),
        ),
    ]
