import type { Access, FieldAccess } from 'payload'

/**
 * Shared access control helpers.
 *
 * The admin role is stored on each user document (`role: 'admin' | 'user'`).
 * We cast `req.user` to a known shape because savedToJWT user types are
 * generated by `pnpm generate:types` and not yet wired here.
 */
type UserShape = {
  id?: string | number
  role?: 'admin' | 'user' | string
  collection?: string
} | null

const getUser = (req: { user?: unknown }): UserShape =>
  (req.user as UserShape) ?? null

/**
 * Allow only admin users.
 */
export const isAdmin: Access = ({ req }) => {
  const user = getUser(req)
  return user?.role === 'admin'
}

/**
 * Allow only admin users (field-level variant).
 */
export const adminOnlyField: FieldAccess = ({ req }) => {
  const user = getUser(req)
  return user?.role === 'admin'
}

/**
 * Allow any authenticated user.
 */
export const authenticatedOnly: Access = ({ req }) => Boolean(getUser(req))

/**
 * Allow admin OR the document owner.
 * Returns a query constraint so it works during list reads too.
 */
export const isAdminOrOwner: Access = ({ req }) => {
  const user = getUser(req)
  if (!user) return false
  if (user.role === 'admin') return true
  if (!user.id) return false
  return { user: { equals: user.id } }
}

/**
 * Allow admin OR the user referenced by `req.user.id` accessing their own row.
 * Used for Users collection.
 */
export const isAdminOrSelf: Access = ({ req, id }) => {
  const user = getUser(req)
  if (!user) return false
  if (user.role === 'admin') return true
  if (!user.id || id === undefined) return false
  return String(user.id) === String(id)
}

/**
 * Admin only, OR published content for everyone.
 * Used for content collections (Houses/Events/News/FAQ) so unauthenticated
 * visitors can read published items but only admins see drafts.
 */
export const adminOrPublished: Access = ({ req }) => {
  const user = getUser(req)
  if (user?.role === 'admin') return true
  return {
    or: [
      { _status: { equals: 'published' } },
      { _status: { exists: false } },
    ],
  }
}
