"""empty message

Revision ID: 9503513bc4ff
Revises: b2edd7b22b75
Create Date: 2025-08-08 18:24:48.102331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9503513bc4ff'
down_revision = 'b2edd7b22b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comfort', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_column('comfort')

    # ### end Alembic commands ###
