"""empty message

Revision ID: 9d10f4dceff1
Revises: 9503513bc4ff
Create Date: 2025-08-08 18:41:24.945469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d10f4dceff1'
down_revision = '9503513bc4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.String(length=300), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
