"""tables

Revision ID: b2edd7b22b75
Revises: 
Create Date: 2025-08-08 18:19:09.040651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2edd7b22b75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bed_house_id'), ['house_id'], unique=False)

    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('bed_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('telegram', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['bed_id'], ['bed.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['house.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_bed_id'), ['bed_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_house_id'), ['house_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_house_id'))
        batch_op.drop_index(batch_op.f('ix_booking_bed_id'))

    op.drop_table('booking')
    with op.batch_alter_table('bed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bed_house_id'))

    op.drop_table('bed')
    op.drop_table('house')
    # ### end Alembic commands ###
