ARG BASE_PYTHON_VERSION=3.12
# --- ЭТАП 1: Базовый образ ---
FROM python:${BASE_PYTHON_VERSION}-slim AS base
# Предотвращаем интерактивные запросы при установке
ENV DEBIAN_FRONTEND=noninteractive

# Копируем бинарник uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

# 1. Системные пакеты (стабильный слой) + ДОБАВЛЕН OpenJDK 21
RUN apt-get update && apt-get install -y --no-install-recommends \
    sudo libpq-dev gettext git jq netcat-openbsd ca-certificates unzip tmux htop curl vim procps \
    gcc libatomic1 fzf zoxide ripgrep bat fd-find build-essential \
    zsh wget  \
    pkg-config \
    clang \
    make cmake \
    less \
    zenity \
    pre-commit \
    ninja-build \
    xz-utils \
    libglu1-mesa \
    libgtk-3-dev \
    libglib2.0-dev \
    libpango1.0-dev \
    libharfbuzz-dev \
    libcairo2-dev \
    mesa-utils \
    lld \
    libnotify-dev \
    llvm \
    postgresql-client \
    fuse \
    lsof \
    file \
    iproute2

# 3. Node.js и Bun (стабильный слой)
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && curl -fsSL https://bun.sh/install | bash \
    && ln -s /root/.bun/bin/bun /usr/local/bin/bun \
    && ln -s /root/.bun/bin/bunx /usr/local/bin/bunx

# 4. Инструменты (Starship, Just, Lazydocker)
RUN curl -sS https://starship.rs/install.sh | sh -s -- -y \
    && curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin \
    && curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash

# 5. Глобальные пакеты (Opencode)
RUN npm install -g opencode-ai \
    --unsafe-perm
