# Generated by Django 5.2.16 on 2026-07-25 00:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 4), ('features', 10), ('text', 11), ('image', 13), ('cta', 15), ('newsletter', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('button_text', 2), ('button_url', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Material Symbol name e.g. 'star', 'home', 'event'", 'max_length': 50, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 8: ('wagtail.blocks.StructBlock', [[('icon', 6), ('text', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('features', 9)]], {}), 11: ('dacha.blocks.RichTextBlock', (), {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('image', 12), ('caption', 5)]], {}), 14: ('wagtail.blocks.URLBlock', (), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('button_text', 7), ('button_url', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Подпишитесь на новости', 'max_length': 200}), 17: ('wagtail.blocks.StructBlock', [[('title', 16), ('description', 1)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
