# Generated by Django 5.2.16 on 2026-07-24 09:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 4), ('features', 10), ('text', 11), ('image', 13), ('cta', 15), ('newsletter', 17)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 100, 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('button_text', 2), ('button_url', 3)]], {}), 5: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "Material Symbol name e.g. 'star', 'home', 'event'", 'max_length': 50, 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 8: ('wagtail.blocks.StructBlock', [[('icon', 6), ('text', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('title', 5), ('features', 9)]], {}), 11: ('dacha.blocks.RichTextBlock', (), {}), 12: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 13: ('wagtail.blocks.StructBlock', [[('image', 12), ('caption', 5)]], {}), 14: ('wagtail.blocks.URLBlock', (), {}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('button_text', 7), ('button_url', 14)]], {}), 16: ('wagtail.blocks.CharBlock', (), {'default': 'Подпишитесь на новости', 'max_length': 200}), 17: ('wagtail.blocks.StructBlock', [[('title', 16), ('description', 1)]], {})}),
        ),
    ]
