# Generated by Django 5.2.16 on 2026-07-25 00:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.StreamField([('paragraph', 0)], blank=True, block_lookup={0: ('dacha.blocks.RichTextBlock', (), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HousePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('capacity', models.IntegerField(default=1)),
                ('bedrooms', models.IntegerField(default=1)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_enabled', models.BooleanField(default=True)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 4)], blank=True, block_lookup={0: ('dacha.blocks.HeadingBlock', (), {}), 1: ('dacha.blocks.RichTextBlock', (), {}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 200, 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
