/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    houses: House;
    events: Event;
    news: News;
    faq: Faq;
    bookings: Booking;
    'event-rsvps': EventRsvp;
    'event-drivers': EventDriver;
    'ride-passengers': RidePassenger;
    'carpool-requests': CarpoolRequest;
    'taxi-pools': TaxiPool;
    'taxi-passengers': TaxiPassenger;
    'newsletter-signups': NewsletterSignup;
    'extra-services': ExtraService;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    houses: HousesSelect<false> | HousesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    'event-rsvps': EventRsvpsSelect<false> | EventRsvpsSelect<true>;
    'event-drivers': EventDriversSelect<false> | EventDriversSelect<true>;
    'ride-passengers': RidePassengersSelect<false> | RidePassengersSelect<true>;
    'carpool-requests': CarpoolRequestsSelect<false> | CarpoolRequestsSelect<true>;
    'taxi-pools': TaxiPoolsSelect<false> | TaxiPoolsSelect<true>;
    'taxi-passengers': TaxiPassengersSelect<false> | TaxiPassengersSelect<true>;
    'newsletter-signups': NewsletterSignupsSelect<false> | NewsletterSignupsSelect<true>;
    'extra-services': ExtraServicesSelect<false> | ExtraServicesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Telegram-authenticated users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  telegramId: string;
  firstName?: string | null;
  lastName?: string | null;
  telegramUsername?: string | null;
  telegramPhotoUrl?: string | null;
  role: 'user' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Загруженные медиа-файлы (картинки, PDF, видео).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt-text для доступности (обязательно)
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Объекты размещения с возможностью онлайн-бронирования.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "houses".
 */
export interface House {
  id: number;
  slug: string;
  title: string;
  summary?: string | null;
  heroImage?: (number | null) | Media;
  capacity?: number | null;
  bedrooms?: number | null;
  address?: string | null;
  /**
   * Базовая цена за ночь в рублях
   */
  basePrice?: number | null;
  /**
   * Можно ли бронировать этот дом через сайт
   */
  bookingEnabled?: boolean | null;
  body?:
    | (
        | {
            text: string;
            level?: ('h2' | 'h3' | 'h4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Мероприятия с RSVP, попутками и такси.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  slug: string;
  title: string;
  startDate: string;
  endDate?: string | null;
  startTime?: string | null;
  venue?: string | null;
  venueNotes?: string | null;
  mapLink?: string | null;
  heroImage?: (number | null) | Media;
  summary?: string | null;
  showCountdown?: boolean | null;
  expectedTemperature?: string | null;
  weatherNote?: string | null;
  specialTag?: string | null;
  /**
   * Сколько человек подтвердили участие
   */
  rsvpCapacity?: number | null;
  body?:
    | (
        | {
            text: string;
            level?: ('h2' | 'h3' | 'h4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            icon?: string | null;
            title: string;
            content?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'infoCard';
          }
        | {
            question: string;
            answer: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqItem';
          }
        | {
            title: string;
            text?: string | null;
            highlighted?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaCard';
          }
        | {
            icon?: string | null;
            label: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'amenityItem';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Новости и анонсы.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  slug: string;
  title: string;
  date: string;
  author?: string | null;
  mainImage?: (number | null) | Media;
  summary?: string | null;
  body?:
    | (
        | {
            text: string;
            level?: ('h2' | 'h3' | 'h4') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            text: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            image: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Страница FAQ — обычно один документ со slug "faq".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  slug: string;
  title: string;
  intro?:
    | {
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'paragraph';
      }[]
    | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * PII — заявки на бронирование. Создаются через /api/bookings/submit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  house: number | House;
  checkIn: string;
  checkOut: string;
  name: string;
  phone: string;
  telegram?: string | null;
  guestNum?: number | null;
  isConfirmed?: boolean | null;
  /**
   * Selected extra services at booking time
   */
  options?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  basePrice?: number | null;
  extrasPrice?: number | null;
  totalPrice?: number | null;
  notes?: string | null;
  totalNights?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * RSVP на события — создаются через /api/event-rsvps/submit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps".
 */
export interface EventRsvp {
  id: number;
  event: number | Event;
  name: string;
  status?: ('going' | 'maybe' | 'not_going' | 'waiting') | null;
  guestsCount?: number | null;
  /**
   * Random UUID; used as identifier in cookies
   */
  secretKey: string;
  /**
   * Optional Telegram user link (for "save RSVP" feature)
   */
  user?: (number | null) | User;
  attendeeSummary?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Водители, готовые подвезти участников на событие.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-drivers".
 */
export interface EventDriver {
  id: number;
  event: number | Event;
  name: string;
  telegram?: string | null;
  phone?: string | null;
  carModel?: string | null;
  carType?: string | null;
  seatsTotal?: number | null;
  departureDate: string;
  departureTime?: string | null;
  departureLocation: string;
  returnDate?: string | null;
  returnTime?: string | null;
  notes?: string | null;
  contactPreference?: ('telegram' | 'phone' | 'both') | null;
  isVerified?: boolean | null;
  isCancelled?: boolean | null;
  /**
   * Auto-generated UUID for cancel-by-token
   */
  cancelToken: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Пассажиры, записавшиеся к водителю.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ride-passengers".
 */
export interface RidePassenger {
  id: number;
  driver: number | EventDriver;
  name: string;
  telegram?: string | null;
  phone?: string | null;
  seats?: number | null;
  pickupLocation?: string | null;
  notes?: string | null;
  status?: ('pending' | 'confirmed' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Запросы «ищу попутку» — кто не может быть водителем.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carpool-requests".
 */
export interface CarpoolRequest {
  id: number;
  event: number | Event;
  name: string;
  telegram?: string | null;
  phone?: string | null;
  pickupLocation?: string | null;
  seatsNeeded?: number | null;
  flexibleTime?: boolean | null;
  canShareGas?: boolean | null;
  notes?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Объединённые поездки на такси (Yandex, Citymobil и др.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxi-pools".
 */
export interface TaxiPool {
  id: number;
  event: number | Event;
  organizer: string;
  telegram?: string | null;
  pickupLocation: string;
  departureDate: string;
  departureTime: string;
  maxPassengers?: number | null;
  estimatedPrice?: string | null;
  service?: ('yandex' | 'citymobil' | 'other') | null;
  notes?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Пассажиры, записавшиеся в общий такси-пул.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxi-passengers".
 */
export interface TaxiPassenger {
  id: number;
  taxi: number | TaxiPool;
  name: string;
  telegram?: string | null;
  phone?: string | null;
  seats?: number | null;
  notes?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * PII — подписчики на рассылку. Подписка через /api/newsletter-signups/subscribe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-signups".
 */
export interface NewsletterSignup {
  id: number;
  email: string;
  subscribedAt: string;
  isActive?: boolean | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Дополнительные услуги (баня, мангал, рыбалка и т.п.).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extra-services".
 */
export interface ExtraService {
  id: number;
  slug: string;
  name: string;
  price?: number | null;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'houses';
        value: number | House;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'event-rsvps';
        value: number | EventRsvp;
      } | null)
    | ({
        relationTo: 'event-drivers';
        value: number | EventDriver;
      } | null)
    | ({
        relationTo: 'ride-passengers';
        value: number | RidePassenger;
      } | null)
    | ({
        relationTo: 'carpool-requests';
        value: number | CarpoolRequest;
      } | null)
    | ({
        relationTo: 'taxi-pools';
        value: number | TaxiPool;
      } | null)
    | ({
        relationTo: 'taxi-passengers';
        value: number | TaxiPassenger;
      } | null)
    | ({
        relationTo: 'newsletter-signups';
        value: number | NewsletterSignup;
      } | null)
    | ({
        relationTo: 'extra-services';
        value: number | ExtraService;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  telegramId?: T;
  firstName?: T;
  lastName?: T;
  telegramUsername?: T;
  telegramPhotoUrl?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "houses_select".
 */
export interface HousesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  summary?: T;
  heroImage?: T;
  capacity?: T;
  bedrooms?: T;
  address?: T;
  basePrice?: T;
  bookingEnabled?: T;
  body?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  startDate?: T;
  endDate?: T;
  startTime?: T;
  venue?: T;
  venueNotes?: T;
  mapLink?: T;
  heroImage?: T;
  summary?: T;
  showCountdown?: T;
  expectedTemperature?: T;
  weatherNote?: T;
  specialTag?: T;
  rsvpCapacity?: T;
  body?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        infoCard?:
          | T
          | {
              icon?: T;
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        faqItem?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
              blockName?: T;
            };
        ctaCard?:
          | T
          | {
              title?: T;
              text?: T;
              highlighted?: T;
              id?: T;
              blockName?: T;
            };
        amenityItem?:
          | T
          | {
              icon?: T;
              label?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  date?: T;
  author?: T;
  mainImage?: T;
  summary?: T;
  body?:
    | T
    | {
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  intro?:
    | T
    | {
        paragraph?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
      };
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  house?: T;
  checkIn?: T;
  checkOut?: T;
  name?: T;
  phone?: T;
  telegram?: T;
  guestNum?: T;
  isConfirmed?: T;
  options?: T;
  basePrice?: T;
  extrasPrice?: T;
  totalPrice?: T;
  notes?: T;
  totalNights?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-rsvps_select".
 */
export interface EventRsvpsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  status?: T;
  guestsCount?: T;
  secretKey?: T;
  user?: T;
  attendeeSummary?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-drivers_select".
 */
export interface EventDriversSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  telegram?: T;
  phone?: T;
  carModel?: T;
  carType?: T;
  seatsTotal?: T;
  departureDate?: T;
  departureTime?: T;
  departureLocation?: T;
  returnDate?: T;
  returnTime?: T;
  notes?: T;
  contactPreference?: T;
  isVerified?: T;
  isCancelled?: T;
  cancelToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ride-passengers_select".
 */
export interface RidePassengersSelect<T extends boolean = true> {
  driver?: T;
  name?: T;
  telegram?: T;
  phone?: T;
  seats?: T;
  pickupLocation?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carpool-requests_select".
 */
export interface CarpoolRequestsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  telegram?: T;
  phone?: T;
  pickupLocation?: T;
  seatsNeeded?: T;
  flexibleTime?: T;
  canShareGas?: T;
  notes?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxi-pools_select".
 */
export interface TaxiPoolsSelect<T extends boolean = true> {
  event?: T;
  organizer?: T;
  telegram?: T;
  pickupLocation?: T;
  departureDate?: T;
  departureTime?: T;
  maxPassengers?: T;
  estimatedPrice?: T;
  service?: T;
  notes?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "taxi-passengers_select".
 */
export interface TaxiPassengersSelect<T extends boolean = true> {
  taxi?: T;
  name?: T;
  telegram?: T;
  phone?: T;
  seats?: T;
  notes?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-signups_select".
 */
export interface NewsletterSignupsSelect<T extends boolean = true> {
  email?: T;
  subscribedAt?: T;
  isActive?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "extra-services_select".
 */
export interface ExtraServicesSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  price?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}