# Generated by Django 5.2.16 on 2026-07-31 14:04

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Доп. услуга',
                'verbose_name_plural': 'Доп. услуги',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки на рассылку',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, default='', max_length=64, verbose_name='Telegram username')),
                ('telegram_first_name', models.CharField(max_length=200, verbose_name='Имя (Telegram)')),
                ('telegram_last_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Фамилия (Telegram)')),
                ('telegram_photo_url', models.URLField(blank=True, default='', verbose_name='Фото (Telegram)')),
                ('auth_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время авторизации в Telegram')),
                ('session_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='Сессия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Последний визит')),
            ],
            options={
                'verbose_name': 'Аккаунт',
                'verbose_name_plural': 'Аккаунты',
            },
        ),
    ]
