# Generated by Django 5.2.16 on 2026-07-30 12:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_telegram_user_account_notnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='auth_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время авторизации в Telegram'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='telegram_first_name',
            field=models.CharField(max_length=200, verbose_name='Имя (Telegram)'),
        ),
    ]
